<?php

drupal_add_css(drupal_get_path('module', 'mydesk_employee') . '/css/mydesk.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));

/*
 * Implement hook_menu()
 */
function mydesk_employee_menu(){
  $items['mydesk/employee'] = array(
    'title' => 'Employee List',
    'page callback' => 'employee_list',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'weight' => 1,
    'file' => 'includes/employee.inc'
  );
  $items['mydesk/employee/add'] = array(
    'title' => 'Employee Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('employee_add'),
    'access callback' => TRUE,
    'file' => 'includes/employee.inc'
  );
  $items['mydesk/departement'] = array(
    'title' => 'Departement List',
    'page callback' => 'departement_list',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'weight' => 1,
    'file' => 'includes/departement.inc'
  );
  $items['mydesk/departement/add'] = array(
    'title' => 'Departement Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('departement_add_form'),
    'access callback' => TRUE,
    'file' => 'includes/departement.inc'
  );
  
  return $items;
}


